; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:sandbox]
platform = atmelsam
board = adafruit_feather_m4
framework = arduino

lib_extra_dirs = ../lib
lib_deps = 
    SystemShared
    https://github.com/adafruit/Adafruit_SleepyDog.git
    https://github.com/adafruit/Adafruit-GFX-Library.git
    https://github.com/adafruit/Adafruit_SSD1306.git

lib_ldf_mode = deep+

; Point Compiler to the Master source and header files
build_flags =
    -D ARDUINO_SAMD_FEATHER_M4
    -I ../ProjectorMaster/include
    -I ../ProjectorMaster/include/drivers
    -I ../ProjectorMaster/include/systemstate
    -I ../ProjectorMaster/include/misc
    -I ../ProjectorMaster/src
    -I ../ProjectorMaster/src/drivers
    -I ../ProjectorMaster/src/systemstate
    -I ../ProjectorSandbox/include/diagnoseDrivers
    -I ../ProjectorSandbox/src/diagnoseDrivers
    -I ../ProjectorSandbox/include/diagnoseSystemState
    -I ../ProjectorSandbox/src/diagnoseSystemState

build_src_filter = 
    +<*> ; Include everything in the Sandbox src
    +<../ProjectorMaster/src/drivers/> ; Compile the Master drivers
    +<../ProjectorMaster/src/systemstate/> ; Compile the Master state machine
    +<../ProjectorMaster/src/> ; Compile other Master source files

; Force a specific COM port if auto upload fails
; upload_port = COM4
; monitor_port = COM4


